openapi: 3.0.1
info:
  title: Common Responses
  version: "1.0"
  description: Shared response definitions used across API specifications
paths: {}
components:
  responses:
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: "./schemas.yaml#/components/schemas/Error"
    NotFound:
      description: Not Found.
      content:
        application/json:
          schema:
            $ref: "./schemas.yaml#/components/schemas/Error"
    InvalidRequestError:
      description: Invalid Request.
      content:
        application/json:
          schema:
            $ref: "./schemas.yaml#/components/schemas/Error"
    ConflictError:
      description: Conflict.
      content:
        application/json:
          schema:
            $ref: "./schemas.yaml#/components/schemas/Error"
    UnauthorizedError:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: "./schemas.yaml#/components/schemas/Error"
    ForbiddenError:
      description: The user is not permitted to access the resource.
      content:
        application/json:
          schema:
            $ref: "./schemas.yaml#/components/schemas/Error"
          example:
            error: "Forbidden"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"
