# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
listen: :8080
# Private key path - used for JWT signing
# Defaults to: /etc/useradm/rsa/private.pem
# Overwrite with environment variable: USERADM_SERVER_PRIV_KEY_PATH
# server_priv_key_path: /etc/useradm/rsa/private.pem

# Private key filename pattern - used to support multiple keys and key rotation
# Each file in a directory where server_priv_key_path reside the service checks
# against the pattern. If the file matches, then it is loaded as a private key
# identified with an id which exists in the file name.
# Defaults to: "private\\.id\\.([0-9]*)\\.pem"
# Overwrite with environment variable: USERADM_SERVER_PRIV_KEY_FILENAME_PATTERN
# server_priv_key_filename_pattern: "private\\.id\\.([0-9]*)\\.pem"

# Fallback private key path - used for JWT verification
# Defaults to: none
# Overwrite with environment variable: USERADM_SERVER_FALLBACK_PRIV_KEY_PATH
# server_fallback_priv_key_path: /etc/useradm/rsa/private-fallback.pem

# JWT issuer ('iss' claim)
# Defaults to: mender.useradm
# jwt_issuer: mender.useradm

# JWT expiration in seconds ('exp' claim)
# Defaults to: "604800" (one week)
# jwt_exp_timeout: 604800

# Mongodb connection string
# Defaults to: mongo-useradm
# mongo: mongo-useradm

# Enable SSL for mongo connections
# Defaults to: false
# mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# mongo_username: user

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# mongo_password: secret

# Maximum number of active sessions (valid JWT tokens) per user
# Defaults to: 10
# limit_sessions_per_user: 10

# Maximum number of peresonal access tokens per user
# Defaults to: 10
# limit_tokens_per_user: 10

# Path to the file containing plan definitions
# Defaults to: "/etc/useradm-enterprise/plans.yaml"
# plan_definitions_path: "/etc/useradm-enterprise/plans.yaml"

# Redis connection string
#
# connectionString URL format:
# Standalone mode:
# (redis|rediss|unix)://[<user>:<password>@](<host>|<socket path>)[:<port>[/<db_number>]][?option=value]
# Cluster mode:
# (redis|rediss|unix)[+srv]://[<user>:<password>@]<host1>[,<host2>[,...]][:<port>][?option=value]
#
# The following query parameters are also available:
# client_name         string
# conn_max_idle_time  duration
# conn_max_lifetime   duration
# dial_timeout        duration
# max_idle_conns      int
# max_retries         int
# max_retry_backoff   duration
# min_idle_conns      int
# min_retry_backoff   duration
# pool_fifo           bool
# pool_size           int
# pool_timeout        duration
# protocol            int
# read_timeout        duration
# tls                 bool
# write_timeout       duration
#
# Defaults to: "", which disables the Redis cache
# Overwrite with environment variable: USERADM_REDIS_CONNECTION_STRING
# redis_connection_string: ""

# Redis key prefix
# Defaults to: "useradm:v1"
# Overwrite with environment variable: USERADM_REDIS_KEY_PREFIX
# redis_key_prefix: ""

# ratelimits:
#  # auth configures ratelimits for authenticated requests.
#   auth:
#     # enable rate limiting also requires redis_connection_string to be effective.
#     enable: false
#     # default rate limit group is the default ratelimiting parameters used when
#     # no group `match`es the expressions.
#     default:
#       quota: 100    # number of request per
#       interval: 60s # interval
#       # event_expression is a go template for grouping requests.
#       # The following attributes are available in the context:
#       # Identity - contains a subset of the JWT claims:
#         - .Subject  (jwt:"sub")          string
#         - .Tenant   (jwt:"mender.tenant) string
#         - .Plan     (jwt:"mender.plan)   string
#         - .Addons   (jwt:"mender.addons) struct{Enabled bool; Name string}
#         - .IsUser   (jwt:"mender.user)   bool
#         - .IsDevice (jwt:"mender.device) bool
#         - .Trial    (jwt:"mender.trial)  bool
#       event_expression: "{{with .Identity}}{{.Subject}}{{end}}"
#     # groups specify rate limiting groups that overrides the parameters in the
#     # default group.
#     groups: []
#     # Example:
#     # - name: "slow"
#     #   quota: 1
#     #   interval: 30s
#     #   event_expression: "{{with .Identity}}{{.Tenant}}{{end}}"
#     # match specifies matching expressions for mapping API requests to rate
#     # limiting groups.
#     match: []
#     # Example:
#     #   # api_pattern specifies an API path pattern as defined by http.ServeMux
#     #   # https://pkg.go.dev/net/http#hdr-Patterns-ServeMux
#     # - api_pattern: /api/management/v1/useradm/slow/api
#     #   # group_expression defines the group for this matching expression.
#     #   # a group can be selected dynamically using Go templates.
#     #   # The template context is the same as ratelimits.default.event_expression
#     #   group_expression: "slow"

# Maximum allowed size for HTTP request bodies (in bytes)
# Defaults to: 1048576 (1 MiB)
# Overwrite with environment variable: USERADM_REQUEST_SIZE_LIMIT

# request_size_limit: 1048576
