openapi: 3.0.3

info:
  title: Device connect
  description: |
    Device facing API for managing persistent device connections.

  version: "1"

# Global security definitions
security:
  - DeviceJWT: []

tags:
  - name: Device API

paths:

  /api/devices/v1/deviceconnect/connect:
    get:
      tags:
        - Device API
      operationId: DeviceConnect Connect
      summary: >-
        Connect the device and make it available to the server.
      description: >-
        Calling /connect will upgrade the connection to a persistent
        websocket connection and make the device available to the
        management API. The device must provide DeviceJWT identity either as
        Authorization (Bearer) header or as a cookie named
        'JWT'.
      parameters:
        - in: header
          name: Connection
          schema:
            type: string
            enum:
              - Upgrade
          description: Standard websocket request header.
        - in: header
          name: Upgrade
          schema:
            type: string
            format: base64
            enum:
              - websocket
          description: Standard websocket request header.
        - in: header
          name: Sec-Websocket-Key
          schema:
            type: string
            format: base64
          description: Standard websocket request header.
        - in: header
          name: Sec-Websocket-Version
          schema:
            type: integer
            enum:
              - 13
          description: Standard websocket request header.
      responses:
        101:
          description: |
            Successful response - change to websocket protocol.
          headers:
            Sec-Websocket-Accept:
              schema:
                type: string
                format: base64
              description: Standard websocket upgrade response header.
            Upgrade:
              schema:
                type: string
                enum:
                  - websocket

        "400":
          $ref: './common/responses.yaml#/components/responses/InvalidRequestError'
        "500":
          $ref: './common/responses.yaml#/components/responses/InternalServerError'


components:
  securitySchemes:
    DeviceJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token issued by 'POST /api/devices/v1/authentication/auth_requests'

  schemas:
