openapi: 3.0.3
info:
  title: Device connect
  description: 'Internal API for managing persistent device connections.

    Intended for use by the web GUI.

    '
  version: '1'
tags:
- name: Internal API
paths:
  /api/internal/v1/deviceconnect/health:
    get:
      tags:
      - Internal API
      summary: Get health status of service
      operationId: DeviceConnect Internal Check Health
      responses:
        204:
          description: Service is healthy.
        '400':
          $ref: ./common/responses.yaml#/components/responses/InvalidRequestError
        '500':
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/alive:
    get:
      tags:
      - Internal API
      summary: Get service liveliness status.
      operationId: DeviceConnect Internal Check Liveliness
      responses:
        204:
          description: Service is up and serving requests.
        '500':
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/shutdown:
    get:
      tags:
      - Internal API
      summary: Shutdown the service.
      operationId: DeviceConnect Internal Shutdown
      responses:
        202:
          description: The service started the graceful shutdown procedure.
        '500':
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/tenants/{tenantId}:
    delete:
      operationId: Delete Tenant
      tags:
      - Internal API
      summary: Delete all the data for given tenant.
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
        required: true
        description: ID of tenant.
      responses:
        204:
          description: All the tenant data have been successfully deleted.
        500:
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/tenants/{tenantId}/devices:
    post:
      tags:
      - Internal API
      operationId: DeviceConnect Internal Provision device
      summary: Register a new device with the deviceconnect service.
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
        required: true
        description: ID of tenant the device belongs to.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './common/schemas.yaml#/components/schemas/ProvisionDevice'
      responses:
        201:
          description: Device was provisioned successfully.
        400:
          $ref: ./common/responses.yaml#/components/responses/InvalidRequestError
        500:
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/tenants/{tenantId}/devices/{deviceId}:
    delete:
      tags:
      - Internal API
      operationId: DeviceConnect Internal Decomission device
      summary: Remove a device from the deviceconnect service.
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
        required: true
        description: ID of tenant the device belongs to.
      - in: path
        name: deviceId
        schema:
          type: string
        required: true
        description: ID of the target device.
      responses:
        202:
          description: Device was deleted successfully
        500:
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/tenants/{tenantId}/devices/{deviceId}/check-update:
    post:
      tags:
      - Internal API
      operationId: DeviceConnect Internal Check Update
      summary: Trigger check-update for the Mender client running on the device
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
        required: true
        description: ID of tenant the device belongs to.
      - in: path
        name: deviceId
        required: true
        schema:
          type: string
        description: ID for the target device.
      responses:
        202:
          description: Accepted
        400:
          $ref: ./common/responses.yaml#/components/responses/InvalidRequestError
        '404':
          $ref: ./common/responses.yaml#/components/responses/NotFound
        '409':
          $ref: ./common/responses.yaml#/components/responses/ConflictError
        500:
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
  /api/internal/v1/deviceconnect/tenants/{tenantId}/devices/{deviceId}/send-inventory:
    post:
      tags:
      - Internal API
      operationId: DeviceConnect Internal Send Inventory
      summary: Trigger send-inventory for the Mender client running on the device
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
        required: true
        description: ID of tenant the device belongs to.
      - in: path
        name: deviceId
        required: true
        schema:
          type: string
        description: ID for the target device.
      responses:
        202:
          description: Accepted
        400:
          $ref: ./common/responses.yaml#/components/responses/InvalidRequestError
        '404':
          $ref: ./common/responses.yaml#/components/responses/NotFound
        '409':
          $ref: ./common/responses.yaml#/components/responses/ConflictError
        500:
          $ref: ./common/responses.yaml#/components/responses/InternalServerError
